FROM ubuntu:20.04
RUN apt-get update
RUN apt-get install -y openjdk-11-jdk
ENV JAVA_HOME/usr
RUN wget https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.85/bin/apache-tomcat-9.0.85.tar.gz
RUN tar-zxvf apache-tomcat-9.0.85.tar.gz/root
COPY target/gamutkart.war/root/apache-tomcat-9.0.85/webapps
ENTRYPOINT /root/apache-tomact-9.0.85/bin/startup.sh && bash 